const SUPPORTED_BROKERS = ['zerodha', 'alpaca'];

const TRADE_TYPES = {
  BUY: 'BUY',
  SELL: 'SELL'
};

const ORDER_TYPES = {
  MARKET: 'MARKET',
  LIMIT: 'LIMIT',
  STOP_LOSS: 'STOP_LOSS',
  STOP_LOSS_MARKET: 'STOP_LOSS_MARKET'
};

const PRODUCT_TYPES = {
  INTRADAY: 'INTRADAY',
  DELIVERY: 'DELIVERY',
  MARGIN: 'MARGIN'
};

const TRADE_STATUS = {
  COMPLETE: 'COMPLETE',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  PENDING: 'PENDING'
};

const TOKEN_EXPIRY = {
  BUFFER_TIME: 5 * 60 * 1000,
  DEFAULT_EXPIRY: 6 * 60 * 60 * 1000
};

module.exports = {
  SUPPORTED_BROKERS,
  TRADE_TYPES,
  ORDER_TYPES,
  PRODUCT_TYPES,
  TRADE_STATUS,
  TOKEN_EXPIRY
};